### ISSUE TITLE
 object has no attribute 'get_location Error

### ISSUE THREAD

**Issue by mailsanchu** [raelgc/gedit-restore-tabs#10]
Traceback (most recent call last):
  File "/home/svarkey/.local/share/gedit/plugins/restoretabs/restoretabs.py", line 47, in on_window_show
    if tab.get_state() == 0 and not tab.get_document().get_location():
AttributeError: 'NoneType' object has no attribute 'get_state'
Traceback (most recent call last):
  File "/home/svarkey/.local/share/gedit/plugins/restoretabs/restoretabs.py", line 37, in on_window_delete_event
    gfile = document.get_location()
AttributeError: 'Document' object has no attribute 'get_location'

**Comment by raelgc** [comment]
Hi @mailsanchu and thanks for reporting this issue.

Which gedit are you using? Which action you've made in order to face this issue?

**Comment by mailsanchu** [comment]
Gedit version is 3.36.2
Just starting up the gedit

**Comment by mailsanchu** [comment]
I did a comparison of the latest master and my version and it is not the same. Let me update

**Comment by mailsanchu** [comment]
It worked and I had the old code and that was the problem. 
Thank you

**Comment by raelgc** [comment]
No problem! I'm glad you got able to solve the issue! Let me know if you find any other issues.
