### ISSUE TITLE
Not working in ubuntu 20.04 

### ISSUE THREAD

**Issue by Electrik-rich546456** [raelgc/gedit-restore-tabs#4]
I have gedit 3.36.2 
I can see the following error if i run it from terminal.

```
gedit

(gedit:17208): Gtk-CRITICAL **: 17:38:01.627: gtk_text_buffer_get_selection_bounds: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(gedit:17208): Gtk-CRITICAL **: 17:38:01.627: gtk_text_buffer_get_selection_bounds: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(gedit:17208): Gtk-CRITICAL **: 17:38:01.627: gtk_text_buffer_get_selection_bounds: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(gedit:17208): Gtk-CRITICAL **: 17:38:01.627: gtk_text_buffer_get_selection_bounds: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

```

**Comment by mattiasw** [comment]
Doesn't work for me either with gedit 3.38.0 (Ubuntu 20.10). When I reopen gedit after having some tabs open it opens without any tabs at all, not even the standard empty one.

**Comment by raelgc** [comment]
I noticed that the latest PR has messed some text formatting, so maybe the instructions in step 3 were not clear. I just fixed.

Please, can you try with the fixed instructions?

If it still doesn't work, you can try with the previous version available in the history (I think you replace directly in your gedit extensions folder (`~/.local/share/gedit/plugins/restoretabs.py`): 

https://github.com/raelgc/gedit-restore-tabs/blob/649f634c015e14e1489d1377f440a5dacd518779/restoretabs.py

**Comment by raelgc** [comment]
Aside fix the instructions, I fixed a small issue for files with blank spaces in the name that started to happen after merge several contributions.

I tested and it worked on Ubuntu 20.04. So, please, update the plugin.

If you're still facing issues, please feel free to re-open this issue.
