### ISSUE TITLE
Problem with space in uri

### ISSUE THREAD

**Issue by iman-zolfaghari** [raelgc/gedit-restore-tabs#6]
Hi there, 
I can work with this plugin without any problem.  There is only a simple bug. The plugin could not restore the files that their addresses contain space. I think you can solve that easily. 
Thanks

**Comment by raelgc** [comment]
@iman-zolfaghari Thanks for reporting this issue. I just tested and this started to happen after merge of #3.

Anyway, I just pushed a fix. Can you test if works for you, please?

**Comment by iman-zolfaghari** [comment]
Very well, It is working properly. 
Many thanks
