### ISSUE TITLE
Not working on Debian 11.0

### ISSUE THREAD

**Issue by ediowar** [raelgc/gedit-restore-tabs#8]
gedit 3.38.1

**Comment by raelgc** [comment]
Hi @ediowar and thanks for raising this issue.

Unfortunately I still don't have an installation with Gedit 3.38 (I'm using Ubuntu 20.04, which has Gedit 3.36 for Gnome 3.38).

By the way, I think Gedit 3.38 has a plugin called "session-saver". Do you mind to test it?

**Comment by ediowar** [comment]
sessionsaver is not maintained https://github.com/bndn/gedit-sessionsaver/issues

**Comment by raelgc** [comment]
There is a gitlab repo for plugins here: https://gitlab.gnome.org/GNOME/gedit-plugins

You can see the session saver here: https://gitlab.gnome.org/GNOME/gedit-plugins/-/tree/master/plugins/sessionsaver

It appears to be a maintained fork. But I didn't test it.

**Comment by ediowar** [comment]
Reinstalled gedit. Plugin works.
